- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# display os version and image name
- name: Display os version
  shell: sudo echo  "System version:" "{{ansible_distribution}}" "{{ansible_distribution_version}}"  |sudo tee -a /data/logs/install_version.txt

- name: Display image name
  shell: sudo echo "Image name:" "{{image}}" |sudo tee -a /data/logs/install_version.txt
  when: image is defined and image is not none

- name: Create docker network connection if dependencies_apps is not null
  shell: docker network connect {{appname}} {{item}}
  with_items: "{{ dependencies_apps }}"
  when: (dependencies_apps is defined) and (dependencies_apps != none)
