- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# Match the role_nodejs where add softlink for Node
- name: Check the nodejs dir exists
  stat:
    path: /opt/nvm/versions/node
  register: nodejs_result

- block:
  - name: Get Node cli lists
    shell: ls /opt/nvm/versions/node/*/bin/
    register: nodejs_clis

  - name: Delete soft link from /usr/bin directory
    file:
      path: '/usr/bin/{{item}}'
      state: absent
    with_items: "{{nodejs_clis.stdout_lines |list}}"
  when: nodejs_result.stat.exists

# Match the role_ruby where add softlink for Node
- name: Check the ruby dir exists
  stat:
    path: /usr/local/rvm/rubies
  register: ruby_result

- block:
  - name: Get ruby version
    shell: ls /usr/local/rvm/rubies |grep ruby
    register: ruby_dir_name

  - name: Get ruby clis
    shell: ls /usr/local/rvm/rubies/{{ruby_dir_name.stdout}}/bin
    register: ruby_clis

  - name: Delete soft link from /usr/bin directory
    file:
      path: '/usr/bin/{{item}}'
      state: absent
    with_items: "{{ruby_clis.stdout_lines |list}}"
  when: ruby_result.stat.exists

# display os version and image name
- block:
  - name: Get system version
    shell: |
      image_name={{image}}
      echo ${image_name##*-}
    register: system_version

  - name: Display os version
    shell: sudo echo  "System version:" "{{system_version.stdout}}"  |sudo tee -a /data/logs/install_version.txt

  - name: Display image name
    shell: sudo echo "Image name:" "{{image}}" |sudo tee -a /data/logs/install_version.txt

  when: image is defined and image is not none