- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Judge file is empty
  shell: |
    [  -s /credentials/password.txt ] && [  -s /credentials/init.sh ] && init_mode=true || init_mode=false
    echo $init_mode
  register: init_mode
  
# if initpass is null or initpasswd file is not exist , stop and exit
- name: Check initpasswd
  fail: msg="initpassword is null,exit!"
  when: init_mode.stdout == "false"
